site_name: integralpesados
site_description: API para el Sistema de Información Integral de la empresa Pesados El Norte
repo_url: https://github.com/leohakim/api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/leohakim">leohakim</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
